### ISSUE TITLE
Love it! Really nice user experience 🤗

### ISSUE THREAD

**Issue by nikkesan** [fac18/week7-coda-squall#34]
Managed to 
- create a new user
- know if i've left any input boxes empty 
- know if my passwords do not match
- see me listed on the leaderboard
- see my cookie in the developer tools
- log out and see my cookie dissappear
- log back in as same user
- see my user details in the database
- see my hashed password in the database
- delete my user 
- see my user deleted in the database too! 

JUST AMAZING!

**Comment by renatajarmova** [comment]
❤️❤️❤️❤️❤️

**Comment by marialani** [comment]
I second this! Well done, you've done an amazing job guys

**Comment by kin-au** [comment]
Yeh, not bad I guess
![](https://media.giphy.com/media/xTiQyBOIQe5cgiyUPS/giphy.gif)

Seriously well done on doing so well and completing all the requirements and more!

**Comment by plasticneuron** [comment]
:blush:
